version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: kusha-elasticsearch
    environment:
      - node.name=kusha-elasticsearch
      - cluster.name=kusha-elastic-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - kusha-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  kusha-app:
    build: .
    ports:
      - "5005:5005"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5005
      - ADMIN_TOKEN=kusha-admin-token-2025
      - SARV_ASR_URL=http://103.255.103.118:5001
      - DATABASE_URL=sqlite:////app/database/kusha_config.db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - DEBUG=False
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - kusha-database:/app/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/api/providers"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kusha-network
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  kusha-network:
    driver: bridge

volumes:
  kusha-data:
    driver: local
  kusha-database:
    driver: local
  elasticsearch-data:
    driver: local